apiVersion: v2
name: mcp-server
description: A Helm chart for MCP Server
version: 0.1.0
appVersion: "1.0.0"
type: application
keywords:
  - mcp
  - server
  - middleware
maintainers:
  - name: middlek
    email: middlek@gmail.com

dependencies:
  - name: ingress-nginx
    version: "4.9.1"
    repository: "https://kubernetes.github.io/ingress-nginx"
  - name: cert-manager
    version: "1.13.2"
    repository: "https://charts.jetstack.io"
    set:
      - name: installCRDs
        value: true
