resources:
  - ../../base
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: mcp-bridge-deployment
    path: deployment.yaml
images:
  - name: middlek/mcp-bridge
    newTag: a93198f2f355a84ff0462c5de448e5a394be3842
  - name: middlek/mcp-context7
    newTag: a93198f2f355a84ff0462c5de448e5a394be3842
