resources:
  - ../../base

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: mcp-bridge-deployment
    path: deployment.yaml

images:
  - name: mcp-bridge
    newTag: latest
  - name: mcp-context7
    newTag: latest
